//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by BVRDE.rc
//
#define IDC_APPLY                       3
#define IDC_ACTIVATE                    3
#define IDC_CLOSE                       4
#define IDD_ABOUTBOX                    100
#define IDD_FILEMISSING                 117
#define IDR_MAIN                        127
#define IDR_MAINFRAME                   128
#define IDR_MDICHILD                    129
#define IDS_SOLUTION                    132
#define IDS_SOULTIONEXPLORER            133
#define IDS_ERR_LOADPROJECT             134
#define IDS_ERR_CREATEPROJECT           135
#define IDS_CAPTION_ERROR               136
#define IDS_CAPTION_QUESTION            137
#define IDS_CAPTION_MESSAGE             138
#define IDS_ERR_PROJECTTYPE             139
#define IDS_ERR_SAVEPROJECT             140
#define IDS_SAVE_DIRTY                  141
#define IDS_FILTER_PROJECT              142
#define IDS_FILTER_SOLUTION             143
#define IDS_SAVE_FIRST                  144
#define IDS_PROPERTIES                  145
#define IDS_MISC                        146
#define IDS_TRUE                        147
#define IDS_FALSE                       148
#define IDS_PROPERTIES_NAME             149
#define IDS_YES                         150
#define IDS_NO                          151
#define IDS_OK                          152
#define IDS_WIZARD_TITLE_SOLUTIONTYPE   153
#define IDS_WIZARD_SUBTITLE_SOLUTIONTYPE 154
#define IDS_PROJECTNAME                 155
#define IDS_WIZARD_NEWPROJECT           156
#define IDS_WIZARD_NEWSOLUTION          157
#define IDS_WIZARD_TITLE_FINISH         158
#define IDS_WIZARD_SUBTITLE_FINISH      159
#define IDS_CAPTION_SAVESOLUTION        160
#define IDS_CAPTION_SAVEPROJECT         161
#define IDS_CAPTION_OUTPUT              162
#define IDS_CAPTION_COMMAND             163
#define IDS_SOLUTIONNAME                164
#define IDS_TREE_ROOT                   165
#define IDS_TREE_ENVIRONMENT            166
#define IDS_TREE_GENERAL                167
#define IDS_TREE_DOCUMENTS              168
#define IDS_TREE_EDITORS                169
#define IDS_TREE_TABS                   170
#define IDS_TREE_FORMATTING             171
#define IDS_TREE_COLORS                 172
#define IDS_TREE_PRINTING               173
#define IDS_ADDIN                       174
#define IDS_KEYBOARD                    175
#define IDS_LAYOUT                      176
#define IDS_MAIN_TOOLBAR                177
#define IDS_TOOLBARS                    178
#define IDS_TREE_CPP                    179
#define IDS_TREE_MAKEFILE               180
#define IDS_TREE_TEXT                   181
#define IDS_TREE_HTML                   182
#define IDS_TREE_XML                    183
#define IDS_TREE_VB                     184
#define IDS_TREE_JAVA                   185
#define IDS_TREE_CSS                    186
#define IDS_TREE_PHP                    187
#define IDS_TREE_PERL                   188
#define IDS_STARTUP_BLANK               189
#define IDS_STARTUP_OPENFILE            190
#define IDS_STARTUP_STARTPAGE           191
#define IDS_CUSTOM                      192
#define IDS_CANCEL                      193
#define IDS_STARTUP_LAST                194
#define IDS_AUTOMATIC                   195
#define IDS_NONE                        196
#define IDS_AUTO                        197
#define IDS_SMART                       198
#define IDS_TYPE_PROJECT                199
#define IDS_TYPE_FILETYPE               200
#define IDS_TYPE_EXTENSION              201
#define IDB_FOLDERS                     202
#define IDS_TYPE                        202
#define IDR_PROJECT                     203
#define IDS_TREE_BASIC                  203
#define IDR_SOLUTION                    203
#define IDS_TREE_ADVANCED               204
#define IDS_CREDITS                     204
#define IDB_EXPLORER                    205
#define IDS_NEWTOOL                     205
#define IDD_CHOOSESOLUTION              206
#define IDS_FILTER_EXE                  206
#define IDB_LOAD1                       207
#define IDS_FILTER_ALL                  207
#define IDB_LOAD2                       208
#define IDS_TREE_SQL                    208
#define IDB_LOAD3                       209
#define IDS_ERR_FILELOCKED              209
#define IDB_PROJECTS                    210
#define IDS_ERR_FILEOPEN                210
#define IDB_PROJECTS32                  210
#define IDI_LOAD1                       211
#define IDS_ERR_VBSCRIPT                211
#define IDI_LOAD2                       212
#define IDB_SPLASH                      212
#define IDS_COMMAND_HELP                212
#define IDI_LOAD3                       213
#define IDB_BANNER                      213
#define IDS_ERR_UNKNOWNCOMMAND          213
#define IDB_WATERMARK                   214
#define IDS_TYPEHELP                    214
#define IDS_ERR_SCRIPT                  215
#define IDR_TOOLIMAGES                  216
#define IDS_TREE_ASSOCIATIONS           216
#define IDS_TREE_ABBREVIATIONS          217
#define IDD_OPTIONS                     218
#define IDS_ASSOC_COL1                  218
#define IDD_WINDOWS                     219
#define IDS_ASSOC_COL2                  219
#define IDD_ADDIN_MANAGER               220
#define IDS_WIZARD_NEWFILE              220
#define IDD_KEYBOARD                    221
#define IDS_WIZARD_TITLE_FILEFINISH     221
#define IDD_CONFIG_KEYBOARD             221
#define IDD_LAYOUT                      222
#define IDS_WIZARD_SUBTITLE_FILEFINISH  222
#define IDD_CONFIG_LAYOUT               222
#define IDD_OPTIONS_GENERAL             223
#define IDS_STATUS_LOADING              223
#define IDD_TOOLS                       224
#define IDS_STATUS_CLOSING              224
#define IDI_NEW                         225
#define IDS_TREE_AUTOTEXT               225
#define IDS_TREE_PASCAL                 226
#define IDS_TREE_PYTHON                 227
#define IDD_MACROS                      228
#define IDS_FULLSCREEN_TOOLBAR          228
#define IDD_CONFIG_MACROS               228
#define IDB_BUILDANIM                   229
#define IDS_FULLSCREEN                  229
#define IDB_PRINTANIM                   230
#define IDS_NEW                         230
#define IDB_TRANSFERANIM                231
#define IDS_ADD                         231
#define IDB_SAVEANIM                    232
#define IDS_STOPRECORDING               232
#define IDM_COOLTAB                     233
#define IDS_CAPTION_SAVEMACRO           233
#define IDR_FULLSCREEN                  234
#define IDS_FILTER_MACRO                234
#define IDS_MACROBIND                   235
#define IDB_PROJECTS16                  235
#define IDI_PROJECT                     236
#define IDS_KEYDUPLICATE                236
#define IDR_OUTPUTVIEW                  237
#define IDS_TREE_ASP                    237
#define IDR_COMMANDVIEW                 238
#define IDS_TOOLTYPE_LOCAL              238
#define IDS_TOOLTYPE_REMOTE             239
#define IDD_ARGUMENTPROMPT              239
#define IDS_TOOLTYPE_COMPILER           239
#define IDS_TOOLTYPE_SQL                240
#define IDM_TOOL_PATH                   240
#define IDS_SOUNDS                      241
#define IDM_TOOL_ARGS                   241
#define IDS_CUSTOMIZE                   242
#define IDS_TOOLTYPE_DEBUGGER           243
#define IDS_EXTERNALTOOL                244
#define IDS_TREE_MAPPINGS               245
#define IDS_LASTVALUE                   246
#define IDS_MAPPING_COL1                247
#define IDS_MAPPING_COL2                248
#define IDS_LANG_DEFAULT                249
#define IDS_LANG_ENGLISH                250
#define IDS_LANG_GERMAN                 251
#define IDS_RESTART                     252
#define IDS_TREE_BASH                   253
#define IDS_ERR_SAVESOLUTION            254
#define IDS_OPENFILES                   255
#define IDS_STATUS_RECMACRO             256
#define IDD_MSGBOX                      263
#define IDI_MSG_INFORMATION             264
#define IDI_MSG_WARNING                 265
#define IDI_MSG_ERROR                   266
#define IDI_MSG_QUESTION                267
#define IDI_DELETE                      268
#define IDI_UP                          269
#define IDI_DOWN                        270
#define IDI_DROPARROW                   271
#define IDI_REFRESH                     272
#define IDC_RADIO1                      1002
#define IDC_RADIO2                      1003
#define IDC_RADIO3                      1004
#define IDC_LIST                        1005
#define IDC_NAME                        1006
#define IDC_SPLASH                      1007
#define IDC_DEFAULT_KEY                 1008
#define IDC_CURRENT_KEY                 1009
#define IDC_NEW_KEY                     1010
#define IDC_ASSIGN                      1011
#define IDC_REMOVE                      1012
#define IDC_PLACEHOLDER                 1016
#define IDC_TAB                         1017
#define IDC_LARGE_ICONS                 1018
#define IDC_LINK                        1020
#define IDC_STARTUP                     1022
#define IDC_READONLY                    1023
#define IDC_LANGUAGE                    1023
#define IDC_DETECT_CHANGE               1024
#define IDC_AUTOLOAD                    1025
#define IDC_SAMPLE                      1026
#define IDC_FINDTEXT                    1027
#define IDC_CLEARUNDO                   1028
#define IDC_WORDWRAP                    1029
#define IDC_FINDMESSAGES                1029
#define IDC_COLORS                      1030
#define IDC_FONTSIZE                    1031
#define IDC_FORE                        1032
#define IDC_BACK                        1033
#define IDC_BOLD                        1034
#define IDC_SAVETOOL                    1035
#define IDC_SAVEPROMPT                  1036
#define IDC_SHOWEDGE                    1037
#define IDC_SHOWEDGE2                   1038
#define IDC_BOTTOMLESS                  1038
#define IDC_CARETWIDTH                  1039
#define IDC_NOAUTOCOMPLETE              1039
#define IDC_NOCLASSBROWSER              1040
#define IDC_CARETLINE                   1040
#define IDC_ONLINESCANNER               1041
#define IDC_MATCHBRACES                 1042
#define IDC_FOLDING                     1043
#define IDC_LINENUMBERS                 1044
#define IDC_INDENTATION                 1045
#define IDC_TABWIDTH                    1046
#define IDC_INDENTWIDTH                 1047
#define IDC_NOTIPS                      1048
#define IDC_PROTECTFILES                1049
#define IDC_EOL                         1050
#define IDC_DOWN                        1051
#define IDC_UP                          1053
#define IDC_DELETE                      1054
#define IDC_NEW                         1055
#define IDC_TITLE                       1056
#define IDC_COMMAND                     1057
#define IDC_BROWSE_FILE                 1058
#define IDC_ARGUMENTS                   1059
#define IDC_USE_OUTPUT                  1060
#define IDC_PATH                        1061
#define IDC_BROWSE_ARGUMENTS            1062
#define IDC_BROWSE_PATH                 1063
#define IDC_USE_TABBED                  1064
#define IDC_PROMPT_ARGS                 1064
#define IDC_USE_MDI                     1065
#define IDC_FONT                        1066
#define IDC_TABINDENTS                  1067
#define IDC_TABINDENT                   1067
#define IDC_BACKUNINDENT                1068
#define IDC_FILES                       1069
#define IDC_USETABS                     1069
#define IDC_CUSTOM_FORE                 1070
#define IDC_CUSTOM_BACK                 1071
#define IDC_ITALICS                     1072
#define IDC_LOADTAGS                    1073
#define IDC_LOADTAGS2                   1074
#define IDC_LOADTAGS3                   1075
#define IDC_MARGINS                     1076
#define IDC_EDIT                        1078
#define IDC_INDENTS                     1078
#define IDC_EDIT2                       1079
#define IDC_HOTKEY                      1082
#define IDC_TYPE                        1085
#define IDC_LAUNCH                      1087
#define IDC_BROWSE                      1088
#define IDC_GREYED                      1089
#define IDC_TEXT                        1148
#define IDC_DONT_SHOW                   1197
#define IDC_DESCRIPTION                 1198
#define IDD_WIZARD_SOLUTIONTYPE         32000
#define IDD_WIZARD_SOLUTIONDONE         32001
#define IDD_CUSOMIZE                    32002
#define IDD_CUSTOMIZE                   32002
#define IDD_OPTIONS_DOCUMENTS           32003
#define IDD_OPTIONS_ASSOCIATIONS        32004
#define IDD_OPTIONS_COLORS              32005
#define IDD_OPTIONS_FORMATTING          32006
#define IDD_OPTIONS_EDITORS             32007
#define IDD_OPTIONS_PRINTING            32008
#define IDD_OPTIONS_DEBUGTEXT           32009
#define IDD_OPTIONS_TAGS                32010
#define IDD_OPTIONS_ALIAS               32011
#define IDD_OPTIONS_AUTOTEXT            32012
#define IDD_MACROBIND                   32013
#define IDD_CONFIG_SOUNDS               32014
#define IDD_OPTIONS_MAPPINGS            32015
#define ID_WINDOW_NEXT                  32796
#define ID_WINDOW_PREVIOUS              32797
#define ID_TOOLS_ADDIN_MANAGER          32803
#define ID_MACRO_SAVE                   32806
#define ID_MACRO_PLAY                   32807
#define ID_MACRO_MANAGER                32809
#define ID_POPUP_NEW                    32810
#define ID_POPUP_ADD                    32811
#define ID_TOOLS_TOOL1                  32812
#define ID_TOOLS_TOOL2                  32813
#define ID_TOOLS_TOOL3                  32814
#define ID_TOOLS_TOOL4                  32815
#define ID_TOOLS_TOOL5                  32816
#define ID_TOOLS_TOOL6                  32817
#define ID_TOOLS_TOOL7                  32818
#define ID_TOOLS_TOOL8                  32819
#define ID_VIEW_PROPERTYBAR             32861
#define ID_TAB_CLOSE                    32862
#define ID_TAB_CLOSEALL                 32863
#define ID_TAB_CLOSEALLEXCEPT           32864
#define ID_TAB_ACTIVATE                 32865
#define ID_VIEW_FULLSCREEN              32866
#define ID_MACROS_KEY1                  32867
#define ID_EDIT_CLEARVIEW               32867
#define ID_MACROS_KEY2                  32868
#define ID_TOOLTOKEN_NAME               32868
#define ID_MACROS_KEY3                  32869
#define ID_TOOLTOKEN_PROJECTPATH        32869
#define ID_MACROS_KEY4                  32870
#define ID_TOOLTOKEN_SELECTION          32870
#define ID_MACROS_KEY5                  32871
#define ID_TOOLTOKEN_HOSTNAME           32871
#define ID_MACROS_KEY6                  32872
#define ID_TOOLTOKEN_PROJECTNAME        32872
#define ID_MACROS_KEY7                  32873
#define ID_TOOLTOKEN_FILENAME           32873
#define ID_MACROS_KEY8                  32874
#define ID_VIEW_OPENFILES               32874
#define ID_MACROS_KEY9                  32875
#define ID_MACROS_KEY10                 32876
#define ID_MACROS_KEY11                 32877
#define ID_MACROS_KEY12                 32878
#define ID_MACROS_KEY13                 32879
#define ID_MACROS_KEY14                 32880
#define ID_MACROS_KEY15                 32881
#define ID_EDIT_CLEAR2                  57638
#define ID_EDIT_COPY2                   57639

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        243
#define _APS_NEXT_COMMAND_VALUE         32875
#define _APS_NEXT_CONTROL_VALUE         1090
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
