//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by SqlProject.rc
//
#define IDR_MAIN                        101
#define IDR_DATABASE                    102
#define IDR_INFO                        102
#define IDR_PROJECT                     103
#define IDB_LISTLARGE                   104
#define IDB_LISTSMALL                   105
#define IDB_TABS                        106
#define IDR_ACCELERATOR                 109
#define IDR_EDIT_LIST                   110
#define IDR_TOOLBAR                     112
#define IDR_MAINFRAME                   200
#define IDR_TOOLIMAGES                  216
#define IDD_WIZARD_PROVIDERS            218
#define IDD_WIZARD_EMPTY                219
#define IDD_WIZARD_CONNECTION           220
#define IDS_CAPTION_ERROR               1000
#define IDC_LIST                        1000
#define IDC_SERVER                      1000
#define IDS_CAPTION_WARNING             1001
#define IDC_DATABASE                    1001
#define IDS_CAPTION_MESSAGE             1002
#define IDC_USERNAME                    1002
#define IDS_ERR_LASTERROR               1003
#define IDC_PASSWORD                    1003
#define IDS_WIZARD_TITLE_PROVIDER       1004
#define IDC_SAVEPASSWORD                1004
#define IDS_WIZARD_SUBTITLE_PROVIDER    1005
#define IDC_CATALOG                     1005
#define IDC_TERMINATOR                  1005
#define IDC_DBTREE                      1006
#define IDS_STATUS_LOADING              1006
#define IDC_MAXROWS                     1006
#define IDC_DBLIST                      1007
#define IDS_HELP                        1007
#define IDC_LIMITRECORDS                1007
#define IDS_WIZARD_TITLE_CONNECTION     1008
#define IDC_MAXERRORS                   1008
#define IDS_WIZARD_SUBTITLE_CONNECTION  1009
#define IDC_LIMITERRORS                 1009
#define IDS_UNKNOWN                     1010
#define IDS_ERR_NOCONNECTION            1011
#define IDS_STDERROR                    1012
#define IDS_STATUS_OPENDATABASE         1013
#define IDS_ERR_OPENVIEW                1014
#define IDS_ERR_DBOPEN                  1015
#define IDS_SQL                         1016
#define IDS_RESULT                      1017
#define IDS_SCHEMA                      1018
#define IDS_SB_POSITION                 1019
#define IDS_TREE_DATABASE               1019
#define IDS_ERR_DOCUMENT                1020
#define IDS_TREE_TABLES                 1020
#define IDS_STATUS_PRINTING             1021
#define IDS_TREE_SYSTEMTABLES           1021
#define IDS_PRINT_TITLE                 1022
#define IDS_TREE_VIEWS                  1022
#define IDS_EXECUTING                   1023
#define IDS_SB_EXECUTING                1023
#define IDS_CAPTION_TOOLBAR             1024
#define IDS_TREE_SP                     1025
#define IDS_TREE_INFO                   1026
#define IDS_DBNAME_LABEL                1027
#define IDS_DBTYPE_LABEL                1028
#define IDS_DBVERSION_LABEL             1029
#define IDS_DBLOCATION_LABEL            1030
#define IDS_DBCATALOG_LABEL             1031
#define IDS_TREE_COLUMNS                1032
#define IDS_TREE_INDICES                1033
#define IDS_DBSERVER_LABEL              1034
#define IDS_DATABASE                    1035
#define IDS_YES                         1036
#define IDS_NO                          1037
#define IDS_INFO_NAME                   1038
#define IDS_INFO_SCHEMA                 1039
#define IDC_AUTOCOMPLETE                1039
#define IDS_INFO_CATALOG                1040
#define IDC_IGNOREVIEWS                 1040
#define IDS_INFO_POSITION               1041
#define IDC_AUTOCOMMIT                  1041
#define IDS_INFO_NULLABLE               1042
#define IDC_STRIPCOMMENTS               1042
#define IDS_INFO_PRIMARY                1043
#define IDC_MATCHBRACES                 1043
#define IDS_INFO_UNIQUE                 1044
#define IDC_BACKGROUNDLOAD              1044
#define IDS_INFO_FLAGS                  1045
#define IDS_INFO_TYPE                   1046
#define IDS_INFO_FIELDS                 1047
#define IDS_INFO_TABLE                  1048
#define IDS_COL_NAME                    1049
#define IDS_COL_VALUE                   1050
#define IDS_INFO_LENGTH                 1051
#define IDS_INFO_PRECISION              1052
#define IDS_INFO_DIGITS                 1053
#define IDS_INFO_HASDEFAULT             1054
#define IDS_INFO_DEFAULT                1055
#define IDS_TYPE_INT                    1056
#define IDS_TYPE_STRING                 1057
#define IDS_TYPE_BOOL                   1058
#define IDS_TYPE_GUID                   1059
#define IDS_TYPE_DATE                   1060
#define IDS_TYPE_TIME                   1061
#define IDS_TYPE_TIMESTAMP              1062
#define IDS_TYPE_BLOB                   1063
#define IDS_TYPE_FLOAT                  1064
#define IDS_TYPE_DOUBLE                 1065
#define IDS_INFO_NULLS                  1066
#define IDS_INFO_CLUSTERED              1067
#define IDS_TAB_SUMMERY                 1068
#define IDS_TAB_RESULT                  1069
#define IDS_SB_DONE                     1070
#define IDS_DBERROR_FORMAT              1071
#define IDS_TRUE                        1072
#define IDS_FALSE                       1073
#define IDS_STANDARD                    1074
#define IDS_TYPE_CURRENCY               1075
#define IDS_ROW_AFFECTED                1076
#define IDS_ROWS_AFFECTED               1077
#define IDS_ROW_SELECTED                1078
#define IDS_ROWS_SELECTED               1079
#define IDS_ERR_FILESAVE                1080
#define IDS_SAVEFILE                    1080
#define IDS_DBERROR_FAILED              1081
#define IDS_TREE_ADVANCED               1082
#define IDS_TREE_SQL                    1083
#define IDS_FILTER_SQL                  1084
#define IDS_CAPTION_QUESTION            1085
#define IDS_NO_ROWS_AFFECTED            1086
#define IDD_OPTIONS_ADVANCED            32009
#define ID_FILE_DELETE                  40003
#define ID_FILE_ADD_REMOTE              40004
#define ID_FILE_RENAME                  40006
#define ID_PROJECT_SET_DEFAULT          40012
#define ID_EDIT_UPPERCASE               40029
#define ID_EDIT_LOWERCASE               40030
#define ID_EDIT_AUTOCOMPLETE            40039
#define ID_EDIT_VIEWWS                  40052
#define ID_EDIT_VIEWEOL                 40060
#define ID_EDIT_TABIFY                  40061
#define ID_EDIT_UNTABIFY                40062
#define ID_EDIT_INDENT                  40063
#define ID_EDIT_UNINDENT                40064
#define ID_EDIT_COMMENT                 40067
#define ID_EDIT_UNCOMMENT               40068
#define ID_VIEW_OPEN_WITH               40069
#define ID_EDIT_VIEWWORDWRAP            40082
#define ID_EDIT_ZOOM_IN                 40086
#define ID_EDIT_ZOOM_OUT                40087
#define ID_EDIT_DELLINE                 40088
#define ID_QUERY_RUN                    40400
#define ID_QUERY_STOP                   40401
#define ID_QUERY_RUNSELECTED            40402
#define ID_RUN_STOP                     40403
#define ID_ADD_DATABASE                 40404
#define ID_DATABASE_DISCONNECT          40406
#define ID_FILE_PROPERTIES              40407
#define ID_HISTORY_DELETE               40408
#define ID_HISTORY_NEW                  40409
#define ID_HISTORY_RIGHT                40410
#define ID_HISTORIK_LEFT                40411
#define ID_QUERY_INSPECT                40412
#define ID_VIEW_TAB1                    40417
#define ID_VIEW_TAB2                    40418
#define ID_VIEW_TAB3                    40419
#define ID_VIEW_SETLINE                 40420

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        107
#define _APS_NEXT_COMMAND_VALUE         40421
#define _APS_NEXT_CONTROL_VALUE         1008
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
