//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by RemoteProject.rc
//
#define IDC_ADD_WATCH                   3
#define IDS_NEW_FOLDER                  100
#define IDR_CPP                         101
#define IDS_FILTER_FILES                101
#define IDR_TEXT                        102
#define IDD_FILEBROWSE                  102
#define IDS_FINDFAILED                  102
#define IDR_PROJECT                     103
#define IDI_BACK                        103
#define IDS_CAPTION_ERROR               103
#define IDR_FOLDER                      104
#define IDI_UP                          104
#define IDS_CAPTION_WARNING             104
#define IDD_FIND                        105
#define IDS_CAPTION_MESSAGE             105
#define IDD_GOTO                        106
#define IDS_CAPTION_TELNETLOG           106
#define IDS_CAPTION_COMPILELOG          106
#define IDD_REPLACE                     107
#define IDS_CAPTION_COMPILE             107
#define IDR_MAIN                        108
#define IDS_CAPTION_COMMAND             108
#define IDS_LOG_TELNETHOST              109
#define IDR_ACCELERATOR                 109
#define IDS_ERR_OPENVIEW                110
#define IDR_EDIT_TEXT                   110
#define IDS_ERR_LASTERROR               111
#define IDR_EDIT_CPP                    111
#define IDS_CAPTION_OUTPUT              112
#define IDR_EDIT_DEBUG                  112
#define IDR_BUILD                       112
#define IDS_LOG_TELNETSEND              113
#define IDS_LOG_SENDERROR               113
#define IDR_CLASSTREE                   113
#define IDS_STATUS_LOADING              114
#define IDR_DEBUG                       114
#define IDM_BOOKMARKS                   114
#define IDS_STATUS_STARTED              115
#define IDR_DISASSEMBLY                 115
#define IDS_STATUS_FINISHED             116
#define IDD_QUICKWATCH                  116
#define IDR_CLASSTREE_ITEM              116
#define IDS_COMPILEBUSY                 117
#define IDS_COMPILE_BUSY                117
#define IDD_CRYPTLIB                    117
#define IDR_MEMORY                      117
#define IDS_ERR_COMPILE                 118
#define IDB_CLASSVIEW                   118
#define IDS_CLEAN                       119
#define IDI_MINUS                       119
#define IDS_REBUILD                     120
#define IDI_PLUS                        120
#define IDS_COMPILE                     121
#define IDI_KEY                         121
#define IDS_BUILDSOLUTION               122
#define IDI_ICON1                       122
#define IDS_LOG_TELNETCONNECT           123
#define IDS_LOG_CONNECTERROR            123
#define IDS_BUILD                       124
#define IDS_WAITCONNECTION              125
#define IDS_CAPTION_QUESTION            126
#define IDS_WIZARD_TITLE_TRANSFER       127
#define IDS_WIZARD_SUBTITLE_TRANSFER    128
#define IDS_WIZARD_TITLE_STARTAPP       129
#define IDS_WIZARD_SUBTITLE_STARTAPP    130
#define IDS_WIZARD_TITLE_DEBUGGER       131
#define IDS_WIZARD_SUBTITLE_DEBUGGER    132
#define IDS_FTP                         133
#define IDS_TELNET                      134
#define IDS_GDB                         135
#define IDS_ERR_NOFTP                   136
#define IDS_ERR_NOCONNECTION            136
#define IDS_CONNECTION_OK               137
#define IDS_STATUS_CONNECT_WAIT         138
#define IDS_CONFIG_TRANSFER             139
#define IDS_CONFIG_COMPILER             140
#define IDS_CONFIG_DEBUGGER             141
#define IDS_CONFIG_SETTINGS             142
#define IDS_COMMANDS                    143
#define IDS_COMMAND_CD                  144
#define IDS_COMMAND_BUILD               145
#define IDS_COMMAND_REBUILD             146
#define IDS_COMMAND_COMPILE             147
#define IDS_COMMAND_CLEAN               148
#define IDS_CONFIG_APPCOMMANDS          149
#define IDS_CONFIG_COMMANDS             149
#define IDS_CAPTION_DEBUGLOG            150
#define IDS_STATUS_RUNNING              151
#define IDS_STATUS_OPENFILE             152
#define IDS_NEEDS_RECOMPILE             153
#define IDS_COMMAND_PARAMS              154
#define IDS_COMMAND_EXECUTE             155
#define IDS_COMMAND_PROXY               156
#define IDS_COMMAND_PASSIVE             157
#define IDS_OPTIONS                     158
#define IDS_CONFIG_OPTIONS              159
#define IDS_DEBUGGER                    160
#define IDS_SB_PANE3                    161
#define IDS_SB_POSITION                 161
#define IDS_TYPEDEF                     161
#define IDS_ERR_TELNETCONNECT           162
#define IDS_ERR_HOSTCONNECT             162
#define IDS_ERR_DATAWRITE               163
#define IDS_ERR_DEBUGGERSTART           164
#define IDS_STATUS_DEBUGGING            165
#define IDS_STATUS_STARTDEBUGGER        166
#define IDS_DEBUGGER_BUSY               167
#define IDS_STATUS_DEBUG_STOPPED        168
#define IDS_STATUS_DEBUG_BREAKPOINT     169
#define IDS_ERR_DEBUG                   170
#define IDS_COMMAND_MAIN                171
#define IDS_ERR_DEBUG_NOTAVAIL          172
#define IDS_ERR_COMPILER_NOTAVAIL       173
#define IDS_STATUS_DEBUG_NOSOURCE       174
#define IDS_CAPTION_CALLSTACK           175
#define IDS_CAPTION_REGISTERS           176
#define IDS_CAPTION_VARIABLES           177
#define IDS_CAPTION_WATCH               178
#define IDS_CAPTION_BREAKPOINTS         179
#define IDS_CAPTION_THREADS             180
#define IDS_THREAD                      181
#define IDS_REGISTER                    182
#define IDS_LOCAL_VARS                  183
#define IDS_CAPTION_BUILD               184
#define IDS_CAPTION_DEBUG               185
#define IDS_STACKLINE                   186
#define IDS_ERR_FILESAVE                187
#define IDS_STOPPED                     188
#define IDS_SIGNAL                      189
#define IDS_DIRECTIVES                  190
#define IDS_COMMAND_DEBUGEXPORT         191
#define IDS_COMMAND_RELEASEEXPORT       192
#define IDS_RELEASE                     193
#define IDS_DEBUG                       194
#define IDS_ERR_FILEINCLUDED            195
#define IDS_SAVECHANGES                 196
#define IDS_STATUS_LOADTAG              197
#define IDS_ERR_DOCUMENT                198
#define IDS_ENUM                        198
#define IDS_STATUS_PRINTING             199
#define IDS_ERR_NODEBUGFILE             199
#define IDS_PRINT_TITLE                 200
#define IDS_BRKCOL1                     200
#define IDS_LOCAL_ARGS                  201
#define IDS_COL_NAME                    202
#define IDS_COL_VALUE                   203
#define IDS_LASTVALUE                   204
#define IDS_STATUS_NETWORKWRITE         205
#define IDS_ERR_NODEBUGINFO             206
#define IDS_STATUS_STOPPED              207
#define IDS_LOG_LOGIN_FAILED            208
#define IDS_LOG_ABORTED                 209
#define IDS_ERR_LOGIN_FAILED            210
#define IDS_ERR_COMPILERBUSY            211
#define IDS_ERR_DEBUGGER_NOT_RUNNING    212
#define IDS_HELP                        213
#define IDS_ERR_COMPILER_NOT_RUNNING    214
#define IDD_WIZARD_FILETRANSFER         215
#define IDS_EXECUTING                   215
#define IDD_WIZARD_APPSTART             216
#define IDR_TOOLIMAGES                  216
#define IDD_WIZARD_COMPILER             216
#define IDS_LOG_RLOGINHOST              216
#define IDD_WIZARD_DEBUGGER             217
#define IDS_RLOGIN                      217
#define IDR_BOOKMARKS                   217
#define IDD_WIZARD_COMMANDS             218
#define IDS_SSH                         218
#define IDR_SEARCH                      218
#define IDS_SCP                         219
#define IDD_PASSWORD                    219
#define IDS_RCP                         220
#define IDS_LOG_SSHHOST                 221
#define IDS_CAPTION_CLASSVIEW           222
#define IDS_GLOBALS                     223
#define IDS_UNKNOWN                     224
#define IDS_CLASS                       225
#define IDS_MEMBER                      226
#define IDS_FUNCTION                    227
#define IDS_STRUCT                      228
#define IDS_DEFINE                      229
#define IDS_ERR_KEY_EXPIRED             230
#define IDS_ERR_KEY_EXPIRES_TODAY       231
#define IDS_ERR_KEY_EXPIRES_SOON        232
#define IDS_STACKLINE2                  233
#define IDS_ERR_BREAKPOINTASYNC         234
#define IDS_STATUS_DEBUG_NOFILE         235
#define IDS_SFTP                        236
#define IDS_TREE_CONFIGURATION          237
#define IDS_CONFIG_CONFIGURATION        238
#define IDS_TREE_ADVANCED               239
#define IDS_TREE_CPP                    240
#define IDS_BRKCOL2                     241
#define IDS_BRKCOL3                     242
#define IDS_BRKCOL4                     243
#define IDS_TOGGLE                      244
#define IDS_GOTO                        245
#define IDS_CAPTION_BOOKMARKS           246
#define IDS_CAPTION_SEARCH              247
#define IDS_SAVEFILE                    248
#define IDS_STACKLINE3                  249
#define IDS_ERR_RELPATH                 250
#define IDS_ERR_DEBUGVERSION            251
#define IDS_CHECKSYNTAX                 252
#define IDS_MISC                        253
#define IDS_COMMAND_BUILDCTAGS          254
#define IDS_COMMAND_CHECKSYNTAX         255
#define IDS_STATUS_SAVEFILE             256
#define IDS_STATUS_LOADFILE             257
#define IDS_CAPTION_DISASSEMBLY         257
#define IDS_CAPTION_MEMORY              258
#define IDS_STATUS_ADDFILE              259
#define IDS_COMMAND_SEARCHPATH          260
#define IDS_MORE                        261
#define IDS_CREATEFILE                  262
#define IDS_CREATEMAKEFILE              263
#define IDS_ERR_NOFILEWIZARD            264
#define IDS_ERR_FILEENCODING            265
#define IDS_COMMAND_COMPILEFLAGS        266
#define IDS_COMMAND_LINKFLAGS           267
#define IDS_ERR_DEBUGUNSTABLE           268
#define IDS_STACKSUBSTR                 269
#define IDS_NETWORKDRIVE                270
#define IDC_LIST                        1000
#define IDC_FOLDER                      1001
#define IDC_BACK                        1003
#define IDC_UP                          1004
#define IDC_SELECTION                   1004
#define IDC_GOLINE                      1005
#define IDC_WHOLEFILE                   1005
#define IDC_CURRLINE                    1006
#define IDC_TYPE                        1006
#define IDC_LASTLINE                    1007
#define IDC_HOST                        1007
#define IDC_USERNAME                    1008
#define IDC_PORT                        1009
#define IDC_PASSWORD                    1010
#define IDC_PATH                        1011
#define IDC_TEST                        1012
#define IDC_EXTRA                       1013
#define IDC_LINE                        1014
#define IDC_DEBUGGER                    1018
#define IDC_TITLE                       1019
#define IDC_LINK                        1020
#define IDC_NOCONNECTION                1023
#define IDC_SUBNOTE                     1024
#define IDC_NOAUTOCOMPLETE              1039
#define IDC_AUTOCOMPLETE                1039
#define IDC_NOCLASSBROWSER              1040
#define IDC_CLASSBROWSER                1040
#define IDC_ONLINESCANNER               1041
#define IDC_MATCHBRACES                 1042
#define IDC_AUTOSUGGEST                 1043
#define IDC_AUTOCLOSE                   1044
#define IDC_MARKERRORS                  1045
#define IDC_NOTIPS                      1048
#define IDC_PROTECTFILES                1049
#define IDC_TYPES_LABEL                 1089
#define IDC_FILENAME_LABEL              1090
#define IDC_TYPES                       1136
#define IDC_FINDTEXT                    1137
#define IDC_WHOLEWORD                   1138
#define IDC_MATCHCASE                   1139
#define IDC_REGEXP                      1140
#define IDC_WRAP                        1141
#define IDC_UNSLASH                     1142
#define IDC_DIRECTIONUP                 1143
#define IDC_DIRECTIONDOWN               1144
#define IDC_MARKALL                     1145
#define IDC_REPLACETEXT                 1146
#define IDC_REPLACE                     1149
#define IDC_REPLACEALL                  1150
#define IDC_REPLACEINSEL                1151
#define IDC_FILENAME                    1152
#define ID_CLASSVIEW_GOTO               1200
#define ID_CLASSVIEW_PROPERTIES         1201
#define ID_CLASSVIEW_COPY               1202
#define IDD_OPTIONS_ADVANCED            32009
#define ID_FILE_OPEN_WITH               40001
#define ID_FILE_COMPILE                 40002
#define ID_FILE_DELETE                  40003
#define ID_FILE_ADD_REMOTE              40004
#define ID_FILE_ADD_LOCAL               40005
#define ID_FILE_RENAME                  40006
#define ID_FILE_PROPERTIES              40007
#define ID_FILE_ADD_FOLDER              40008
#define ID_PROJECT_SET_DEFAULT          40012
#define ID_PROJECT_SAVE                 40013
#define ID_BUILD_SOLUTION               40014
#define ID_BUILD_REBUILD                40015
#define ID_BUILD_CLEAN                  40016
#define ID_BUILD_PROJECT                40017
#define ID_BUILD_COMPILE                40018
#define ID_DEBUG_START                  40019
#define ID_DEBUG_DEBUG                  40020
#define ID_DEBUG_PROCESSES              40021
#define ID_DEBUG_STEP_INTO              40022
#define ID_DEBUG_STEP_OVER              40023
#define ID_DEBUG_BREAKPOINT             40024
#define ID_DEBUG_CLEAR_BREAKPOINTS      40025
#define ID_VIEW_WATCH                   40026
#define ID_VIEW_CALLSTACK               40027
#define ID_VIEW_BREAKPOINTS             40028
#define ID_EDIT_UPPERCASE               40029
#define ID_EDIT_LOWERCASE               40030
#define ID_BOOKMARK_NEXT                40031
#define ID_BOOKMARK_PREVIOUS            40032
#define ID_BOOKMARK_CLEAR               40033
#define ID_VIEW_COMPILE_LOG             40034
#define ID_DEBUG_STOP                   40035
#define ID_DEBUG_THREADS                40036
#define ID_DEBUG_QUICKWATCH             40037
#define ID_DEBUG_GOTO_CURRENT           40038
#define ID_EDIT_AUTOCOMPLETE            40039
#define ID_VIEW_DEBUG_LOG               40042
#define ID_BOOKMARK_TOGGLE              40043
#define ID_BUILD_STOP                   40044
#define ID_DEBUG_STEP_OUT               40046
#define ID_DEBUG_STEP_RUN               40047
#define ID_DEBUG_EDIT_LINK              40048
#define ID_VIEW_VARIABLES               40049
#define ID_VIEW_THREADS                 40050
#define ID_VIEW_REGISTERS               40051
#define ID_EDIT_VIEWWS                  40052
#define ID_EDIT_VIEWEOL                 40060
#define ID_EDIT_TABIFY                  40061
#define ID_EDIT_UNTABIFY                40062
#define ID_EDIT_INDENT                  40063
#define ID_EDIT_UNINDENT                40064
#define ID_DEBUG_STEP_SET               40065
#define ID_EDIT_COMMENT                 40067
#define ID_EDIT_UNCOMMENT               40068
#define ID_VIEW_OPEN_WITH               40069
#define ID_DEBUG_BREAK                  40079
#define ID_EDIT_VIEWWORDWRAP            40082
#define ID_EDIT_BREAK                   40083
#define ID_EDIT_ZOOM_IN                 40086
#define ID_EDIT_ZOOM_OUT                40087
#define ID_EDIT_DELLINE                 40088
#define ID_SEARCH_GO                    40092
#define ID_BOOKMARKS_TOGGLE             40099
#define ID_BOOKMARKS_GOTO               40100
#define ID_BOOKMARKS_GOTO1              40101
#define ID_BOOKMARKS_GOTO2              40102
#define ID_BOOKMARKS_GOTO3              40103
#define ID_BOOKMARKS_GOTO4              40104
#define ID_BOOKMARKS_GOTO5              40105
#define ID_BOOKMARKS_GOTO6              40106
#define ID_BOOKMARKS_GOTO7              40107
#define ID_BOOKMARKS_GOTO8              40108
#define ID_BOOKMARS_SET                 40109
#define ID_BUILD_CHECKSYNTAX            40110
#define ID_BUILD_BUILDTAGS              40111
#define ID_BUILD_BUILDMAKEFILE          40112
#define ID_VIEW_MEMORY                  40114
#define ID_VIEW_DISASM                  40115
#define ID_BUILD_FILEWIZARD             40116
#define ID_DISASM_INTELSTYLE            40117
#define ID_DISASM_SHOWSOURCE            40118
#define ID_CLASSVIEW_SORT               40121
#define ID_CLASSVIEW_NOSORT             40122
#define ID_MEMORY_EDIT                  40123
#define ID_MEMORY_SIZE_DWORD            40124
#define ID_MEMORY_SIZE_WORD             40125
#define ID_MEMORY_SIZE_BYTE             40126
#define ID_MEMORY_REFRESH               40127

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        124
#define _APS_NEXT_COMMAND_VALUE         40128
#define _APS_NEXT_CONTROL_VALUE         1025
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
