//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by SourceControl.rc
//
#define IDR_SOURCECONTROL               101
#define IDR_DIFF                        102
#define IDB_OVERLAY                     103
#define IDD_FINDFILES                   105
#define IDD_CHECKIN                     105
#define IDD_OPTIONS_COMMANDS            218
#define IDD_CVS_LOGIN                   219
#define IDD_ADDFILE                     220
#define IDD_UPDATE                      221
#define IDD_OPTIONS_DIFF                222
#define IDS_TITLE                       1000
#define IDC_FILES                       1000
#define IDC_LIST                        1000
#define IDS_SEARCHING                   1001
#define IDC_COMMENT                     1001
#define IDS_CAPTION                     1001
#define IDS_REPOSITORY                  1002
#define IDC_TYPE                        1002
#define IDC_PASSWORD                    1002
#define IDS_GROUP_PROGRAM               1003
#define IDC_CONNECT                     1003
#define IDS_GROUP_COMMANDS              1004
#define IDC_SERVER                      1004
#define IDS_GROUP_OPTIONS               1005
#define IDC_USERNAME                    1005
#define IDS_PROGRAM_APP                 1006
#define IDC_CTYPE                       1006
#define IDS_COMMAND_CHECKIN             1007
#define IDC_PATH                        1007
#define IDC_DIRS                        1007
#define IDS_COMMAND_CHECKOUT            1008
#define IDC_BRANCH                      1008
#define IDS_COMMAND_UPDATE              1009
#define IDC_BRANCHTEXT                  1009
#define IDS_COMMAND_LOGIN               1010
#define IDC_WORDWRAP                    1010
#define IDS_COMMAND_LOGOUT              1011
#define IDC_LISTUNCHANGED               1011
#define IDS_COMMAND_STATUS              1012
#define IDS_COMMAND_DIFF                1013
#define IDS_COMMAND_ADDFILE             1014
#define IDS_COMMAND_REMOVEFILE          1015
#define IDS_SYSTEM_CVS                  1016
#define IDS_SYSTEM_SOURCESAFE           1017
#define IDS_TREE_SOURCECONTROL          1018
#define IDS_TREE_COMMANDS               1019
#define IDS_TREE_ROOT                   1020
#define IDS_OPTIONS_STICKYTAG           1021
#define IDS_OPTIONS_OVERWRITE           1022
#define IDS_OPTIONS_MESSAGE             1023
#define IDS_OPTIONS_RECURSIVE           1024
#define IDS_SYSTEM_NONE                 1025
#define IDS_OPTION_MESSAGE              1026
#define IDS_OPTION_RECURSIVE            1027
#define IDS_OPTION_STICKYTAGS           1028
#define IDS_MISC_OUTPUT                 1029
#define IDS_GROUP_MISC                  1030
#define IDS_SYSTEM_CUSTOM               1031
#define IDC_FONTSIZE                    1031
#define IDS_TYPE_LOCAL                  1032
#define IDS_TYPE_EXT                    1033
#define IDS_TYPE_PSERVER                1034
#define IDS_TYPE_SERVER                 1035
#define IDS_OPTION_UPDATEDIRS           1036
#define IDS_OPTION_BRANCH               1037
#define IDS_FILES                       1038
#define IDS_OPTION_GENERAL              1039
#define IDS_GROUP_BROWSER               1040
#define IDS_BROWSER_ALL                 1041
#define IDS_BROWSER_SINGLE              1042
#define IDS_BUILDING                    1043
#define IDS_NOTCONFIGURED               1044
#define IDS_SYSTEM_SUBVERSION           1045
#define IDS_CAPTION_DIFF                1046
#define IDS_DIFF_LEFTFILE               1047
#define IDS_DIFF_RIGHTFILE              1048
#define IDS_EMPTY                       1049
#define IDS_DIFF_FIRSTCHANGE            1050
#define IDS_STATUS_DIFFVIEW             1051
#define IDS_DIFF_GENERALFILE            1052
#define IDS_TREE_DIFF                   1053
#define IDS_LEFTLINE                    1054
#define IDS_RIGHTLINE                   1055
#define IDS_NOPROJECT                   1056
#define IDC_FONT                        1066
#define IDC_FINDTEXT                    1137
#define IDC_WHOLEWORD                   1138
#define IDC_KEEPOUT                     1138
#define IDC_MATCHCASE                   1139
#define IDC_RESETSTICKS                 1139
#define IDC_REGEXP                      1140
#define IDC_SUBFOLDERS                  1141
#define IDC_FOLDER                      1142
#define IDC_SC_CHANGEDIR                1143
#define ID_VIEW_REPOSITORY              42000
#define ID_SC_UPDATE                    42010
#define ID_SC_CHECKIN                   42011
#define ID_SC_CHECKOUT                  42012
#define ID_SC_LOGIN                     42013
#define ID_SC_DIFFVIEW                  42014
#define ID_SC_ADDFILE                   42015
#define ID_SC_REMOVEFILE                42016
#define ID_SC_STATUS                    42017
#define ID_SC_LOGOUT                    42018

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        104
#define _APS_NEXT_COMMAND_VALUE         42019
#define _APS_NEXT_CONTROL_VALUE         1011
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
